// <auto-generated />
using System;
using EF_CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF_CodeFirst.Models.Dbo.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"), 1L, 1);

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "Grade 1",
                            Section = "Section 1",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "Grade 2",
                            Section = "Section 2",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "Grade 3",
                            Section = "Section 3",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "Grade 4",
                            Section = "Section 4",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "Grade 5",
                            Section = "Section 5",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "Grade 6",
                            Section = "Section 6",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "Grade 7",
                            Section = "Section 7",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Dbo.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("StudentId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(2001, 6, 29, 19, 52, 7, 309, DateTimeKind.Local).AddTicks(3260),
                            Height = 185m,
                            StudentName = "John Doe",
                            Weight = 85f
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(1999, 6, 29, 19, 52, 7, 309, DateTimeKind.Local).AddTicks(3290),
                            Height = 160m,
                            StudentName = "Jane Doe",
                            Weight = 75f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
